name: build java-base

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - java/**

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  push:
    name: "java:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          #- 8
          #- 11
          #- 16
          - 17
          #- 18
          #- 19
          #- 20
          #- 21
          #- 22

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./java
          file: ./java/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/moritz-deiaco/java:${{ matrix.tag }}
